name: Add PR sizing label

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  add-pr-size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install PR sizing label script
        run: |
          # Clone into a temporary directory to avoid overwriting
          # any existing github directory.
          pushd $(mktemp -d) &>/dev/null
          git clone --single-branch --depth 1 "https://github.com/jamesodhunt-org/.github" && cd .github/scripts
          sudo install add-pr-size-label.sh /usr/local/bin
          popd &>/dev/null

      - name: Add PR sizing label
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PR_SIZE_LABEL_SECRET }}
        run: |
          pr=${{ github.event.number }}

          sudo apt -y install diffstat

          add-pr-size-label.sh "$pr"
