name: Test GHA steps

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  test-gha-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |

        # Force action to be enabled
        echo "::set-output name=action_enabled::true"
        echo "::set-output name=JAMES::1"

        echo "::debug::step-1: normal env action_enabled: '$action_enabled'"
        echo "::debug::step-1: gh env action_enabled: ${{ env.action_enabled}}"

        echo "::debug::step-1: normal env JAMES: '$JAMES'"
        echo "::debug::step-1: gh env JAMES: ${{ env.JAMES }}"

      - name: Step 2
        run: |
        echo "::debug::step-2: normal env action_enabled: '$action_enabled'"
        echo "::debug::step-2: gh env action_enabled: ${{ env.action_enabled}}"

        echo "::debug::step-2: normal env JAMES: '$JAMES'"
        echo "::debug::step-2: gh env JAMES: ${{ env.JAMES }}"

      - name: Step 3
        if: ${{ env.action_enabled == 'true' }}
        run: |
        echo "::debug::step-3: normal env action_enabled: '$action_enabled'"
        echo "::debug::step-3: gh env action_enabled: ${{ env.action_enabled}}"

        echo "::debug::step-3: normal env JAMES: '$JAMES'"
        echo "::debug::step-3: gh env JAMES: ${{ env.JAMES }}"

      - name: Step 4 (change var)
        run: |

        # XXX: Change env var
        echo "::set-output name=JAMES::3"

        echo "::debug::step-4: normal env action_enabled: '$action_enabled'"
        echo "::debug::step-4: gh env action_enabled: ${{ env.action_enabled}}"

        echo "::debug::step-4-change-var: normal env JAMES: '$JAMES'"
        echo "::debug::step-4-change-var: gh env JAMES: ${{ env.JAMES }}"

      - name: Step 5
        run: |
        echo "::debug::step-5: normal env action_enabled: '$action_enabled'"
        echo "::debug::step-5: gh env action_enabled: ${{ env.action_enabled}}"

        echo "::debug::step-5: normal env JAMES: '$JAMES'"
        echo "::debug::step-5: gh env JAMES: ${{ env.JAMES }}"

      - name: Step 6
        run: |
        echo "::debug::step-6: normal env action_enabled: '$action_enabled'"
        echo "::debug::step-6: gh env action_enabled: ${{ env.action_enabled}}"

        echo "::debug::step-6: normal env JAMES: '$JAMES'"
        echo "::debug::step-6: gh env JAMES: ${{ env.JAMES }}"
